# Generated by Django 4.2.20 on 2025-04-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=100, unique=True, verbose_name='İngilizce Kelime')),
                ('tur_word', models.CharField(max_length=100, verbose_name='Türkçe Karşılık')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('samples', models.TextField(verbose_name='Örnek Cümleler')),
                ('correct_count', models.IntegerField(default=0)),
                ('correct_date', models.DateField(blank=True, null=True)),
                ('next_show_date', models.DateField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
    ]
