# Generated by Django 4.2.20 on 2025-04-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelimeler', '0002_word_word_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_type',
            field=models.CharField(choices=[('noun', 'İsim'), ('verb', 'Fiil'), ('adj', 'Sıfat'), ('adv', 'Zarf'), ('pron', 'Zamir'), ('other', 'Diğer')], default='other', max_length=10),
        ),
    ]
