# Generated by Django 4.2.20 on 2025-04-23 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kelimeler', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('total_questions', models.IntegerField()),
                ('verb_total', models.IntegerField(default=0)),
                ('verb_correct', models.IntegerField(default=0)),
                ('noun_total', models.IntegerField(default=0)),
                ('noun_correct', models.IntegerField(default=0)),
                ('adjective_total', models.IntegerField(default=0)),
                ('adjective_correct', models.IntegerField(default=0)),
                ('adverb_total', models.IntegerField(default=0)),
                ('adverb_correct', models.IntegerField(default=0)),
                ('other_total', models.IntegerField(default=0)),
                ('other_correct', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField()),
                ('total_wrong', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
